export DEPS="/home/markgunnels75/noylitics/deps"
export NODE_EXPAT="$DEPS/node-expat/build/default"
export NODE_XMLJS="$DEPS/libxmljs"
export NODE_XML="$DEPS/node-xml/lib"
export NODE_TWITTER="$DEPS/twitter-node/lib/twitter-node"
export NODE_HTMLPARSER="$DEPS/node-htmlparser"
export NODE_XMPP="$DEPS/node-xmpp/lib/"
export NODE_BASE64="$DEPS/node-base64/build/default"
export NODE_PATH="$NODE_PATH:$NODE_EXPAT:$NODE_XMLJS:$NODE_XML:$NODE_XMPP:$NODE_BASE64:$NODE_EXPAT/node-expat:$NODE_HTMLPARSER:$NODE_TWITTER"

