export DEPS="/home/markgunnels75/noylitics/deps"
export NODE_EXPAT="$DEPS/node-expat/build/default"
export NODE_XMPP="$DEPS/node-xmpp/lib/"
export NODE_BASE64="$DEPS/node-base64/build/default"
export NODE_PATH="$NODE_PATH:$NODE_EXPAT:$NODE_XMPP:$NODE_BASE64"
